### ISSUE TITLE
Unable to reproduce a memory leak that exists only when a function is decorated with `@jit(nopython=True)`. Suggestions?

### ISSUE THREAD

**Issue by bmer** [numba/numba#1290]
Hi all,

I am coming across a situation when running my simulation where numba-fying a particular function leads to memory leaks (in Spyder, I can see the memory usage increasing approximately 3% per second, on my 4 GB RAM system). This eventually leads to my simulation crashing.

I am having lots of trouble reproducing the memory leak in a simple working example. Here is one trial at writing a minimal not-working example that attempts to model what my code does (basically, "disconnected" integration): https://gist.github.com/bmer/68afd05bf5f3c3383966

It does not cause a memory leak. :(

What can I do in order to figure out what is causing the memory leak, allowing me to make a simple example of it, so that I can share it here and get it fixed?

Kind regards,
Brian

**Comment by seibert** [comment]
We have fixed a few reference counting errors in Numba in the last week.  Which version of Numba are you using?

More broadly, we should add a debug function that can dump a list of all the NRT-allocated memory chunks.

**Comment by bmer** [comment]
Hi Stan,

I am using the latest numba available through `conda install -c numba numba`, as of three or four hours ago. When I find a numba problem, my first step is always to update it. 

It would be awesome if a debug function could be added!

**Comment by bmer** [comment]
I was able to track down the issue by slowly disabling portions of my code that did not contribute to the issue (i.e. I would comment out bits, and check to see that the issue was still occurring). See this issue for the resulting minimal not working script: https://github.com/numba/numba/issues/1291
