### ISSUE TITLE
simple assignment in a jit-ed function prevents nopython mode

### ISSUE THREAD

**Issue by WeatherGod** [numba/numba#1372]
Consider the following:
```
from __future__ import print_function
from numba import jit
import numpy as np


@jit
def func1(fromLons, fromLats, toLons, toLats):
    return (np.radians(fromLons),
            np.radians(fromLats),
            np.radians(toLons),
            np.radians(toLats))

@jit
def func2(fromLons, fromLats, toLons, toLats):
    # Haversine formula
    return (6371.0 * 2.0 * np.arcsin(np.sqrt(np.sin((toLats - fromLats)/2.0) ** 2
                          + np.cos(fromLats) * np.cos(toLats)
                        * np.sin((toLons - fromLons)/2.0) ** 2)))

@jit
def distance(fromLons, fromLats, toLons, toLats):
    return func2(*func1(fromLons, fromLats, toLons, toLats))

@jit
def distance2(fromLons, fromLats, toLons, toLats):
    fromLons = np.radians(fromLons)
    fromLats = np.radians(fromLats)
    toLons = np.radians(toLons)
    toLats = np.radians(toLats)

    # Haversine formula
    return (6371.0 * 2.0 * np.arcsin(np.sqrt(np.sin((toLats - fromLats)/2.0) ** 2
                          + np.cos(fromLats) * np.cos(toLats)
                        * np.sin((toLons - fromLons)/2.0) ** 2)))

if __name__ == '__main__':
    a = np.linspace(0, 360, 20)
    b = np.linspace(10, 55, 25)

    distance(a, b[:20], 1.75, 1.5)
    #distance(a[:, None], b[None, :], 1.75, 1.5)
    distance2(a, b[:20], 1.75, 1.5)
    #distance2(a[:, None], b[None, :], 1.75, 1.5)

    print("distance() types:\n", distance.inspect_types())
    print("\ndistance2() types:\n", distance2.inspect_types())
```
Ignore for the moment that this isn't actually *the* Haversine formula. `distance()` and `distance2()` produce the same results, but `distance()` is implemented by calling `func1()` and `func2()`, thereby avoiding an explicit assignment step seen in `distance2()`. This assignment step is apparently preventing numba from going into nopython mode. It seems like a silly little thing to me given that numba knows what the output of `np.radians()` is.

I am using v0.20.0 from miniconda. I included the output from the `inspect_types()` below.

BTW, notice that I commented out a couple of calls to `distance()` and `distance2()`. If I include them, I get a TypeError, stating that "TypeError: not enough arguments: expected 4, got 0". Don't know if it is related or not, but it irked me to no end.

```
distance (array(float64, 1d, C), array(float64, 1d, C), float64, float64)
--------------------------------------------------------------------------------
# File: numbatest.py
# --- LINE 20 --- 

@jit

# --- LINE 21 --- 

def distance(fromLons, fromLats, toLons, toLats):

    # --- LINE 22 --- 
    # label 0
    #   fromLons = arg(0, name=fromLons)  :: array(float64, 1d, C)
    #   fromLats = arg(1, name=fromLats)  :: array(float64, 1d, C)
    #   toLons = arg(2, name=toLons)  :: float64
    #   toLats = arg(3, name=toLats)  :: float64
    #   $0.1 = global(func2: CPUOverloaded(<function func2 at 0x7fef11b2fde8>))  :: Dispatcher(CPUOverloaded(<function func2 at 0x7fef11b2fde8>))
    #   $0.2 = global(func1: CPUOverloaded(<function func1 at 0x7fef11b2fc80>))  :: Dispatcher(CPUOverloaded(<function func1 at 0x7fef11b2fc80>))
    #   $0.7 = call $0.2(fromLons, fromLats, toLons, toLats)  :: (array(float64, 1d, C), array(float64, 1d, C), float64, float64) -> (array(float64, 1d, C), array(float64, 1d, C), float64, float64)
    #   del toLons
    #   del toLats
    #   del fromLons
    #   del fromLats
    #   del $0.2
    #   $0.8 = call $0.1(*$0.7)  :: (array(float64, 1d, C), array(float64, 1d, C), float64, float64) -> array(float64, 1d, C)
    #   del $0.7
    #   del $0.1
    #   $0.9 = cast(value=$0.8)  :: array(float64, 1d, C)
    #   del $0.8
    #   return $0.9

    return func2(*func1(fromLons, fromLats, toLons, toLats))


================================================================================
distance() types:
 None
distance2 (array(float64, 1d, C), array(float64, 1d, C), float64, float64)
--------------------------------------------------------------------------------
# File: numbatest.py
# --- LINE 24 --- 

@jit

# --- LINE 25 --- 

def distance2(fromLons, fromLats, toLons, toLats):

    # --- LINE 26 --- 
    # label 0
    #   fromLons = arg(0, name=fromLons)  :: pyobject
    #   fromLats = arg(1, name=fromLats)  :: pyobject
    #   toLons = arg(2, name=toLons)  :: pyobject
    #   toLats = arg(3, name=toLats)  :: pyobject
    #   $0.1 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.2 = getattr(attr=radians, value=$0.1)  :: pyobject
    #   del $0.1
    #   $0.4 = call $0.2(fromLons)  :: pyobject
    #   del fromLons
    #   del $0.2
    #   fromLons.1 = $0.4  :: pyobject
    #   del $0.4

    fromLons = np.radians(fromLons)

    # --- LINE 27 --- 
    #   $0.5 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.6 = getattr(attr=radians, value=$0.5)  :: pyobject
    #   del $0.5
    #   $0.8 = call $0.6(fromLats)  :: pyobject
    #   del fromLats
    #   del $0.6
    #   fromLats.1 = $0.8  :: pyobject
    #   del $0.8

    fromLats = np.radians(fromLats)

    # --- LINE 28 --- 
    #   $0.9 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.10 = getattr(attr=radians, value=$0.9)  :: pyobject
    #   del $0.9
    #   $0.12 = call $0.10(toLons)  :: pyobject
    #   del toLons
    #   del $0.10
    #   toLons.1 = $0.12  :: pyobject
    #   del $0.12

    toLons = np.radians(toLons)

    # --- LINE 29 --- 
    #   $0.13 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.14 = getattr(attr=radians, value=$0.13)  :: pyobject
    #   del $0.13
    #   $0.16 = call $0.14(toLats)  :: pyobject
    #   del toLats
    #   del $0.14
    #   toLats.1 = $0.16  :: pyobject
    #   del $0.16

    toLats = np.radians(toLats)

# --- LINE 30 --- 



    # --- LINE 31 --- 

    # Haversine formula

    # --- LINE 32 --- 
    #   $const0.17 = const(float, 12742.0)  :: pyobject
    #   $0.18 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.19 = getattr(attr=arcsin, value=$0.18)  :: pyobject
    #   del $0.18
    #   $0.20 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.21 = getattr(attr=sqrt, value=$0.20)  :: pyobject
    #   del $0.20
    #   $0.22 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.23 = getattr(attr=sin, value=$0.22)  :: pyobject
    #   del $0.22
    #   $0.26 = toLats.1 - fromLats.1  :: pyobject
    #   $const0.27 = const(float, 2.0)  :: pyobject
    #   $0.28 = $0.26 /? $const0.27  :: pyobject
    #   del $const0.27
    #   del $0.26
    #   $0.29 = call $0.23($0.28)  :: pyobject
    #   del $0.28
    #   del $0.23
    #   $const0.30 = const(int, 2)  :: pyobject
    #   $0.31 = $0.29 ** $const0.30  :: pyobject
    #   del $const0.30
    #   del $0.29

    return (6371.0 * 2.0 * np.arcsin(np.sqrt(np.sin((toLats - fromLats)/2.0) ** 2

                          # --- LINE 33 --- 

                          + np.cos(fromLats) * np.cos(toLats)

                        # --- LINE 34 --- 
                        #   $0.32 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
                        #   $0.33 = getattr(attr=cos, value=$0.32)  :: pyobject
                        #   del $0.32
                        #   $0.35 = call $0.33(fromLats.1)  :: pyobject
                        #   del fromLats.1
                        #   del $0.33
                        #   $0.36 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
                        #   $0.37 = getattr(attr=cos, value=$0.36)  :: pyobject
                        #   del $0.36
                        #   $0.39 = call $0.37(toLats.1)  :: pyobject
                        #   del toLats.1
                        #   del $0.37
                        #   $0.40 = $0.35 * $0.39  :: pyobject
                        #   del $0.39
                        #   del $0.35
                        #   $0.41 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
                        #   $0.42 = getattr(attr=sin, value=$0.41)  :: pyobject
                        #   del $0.41
                        #   $0.45 = toLons.1 - fromLons.1  :: pyobject
                        #   del toLons.1
                        #   del fromLons.1
                        #   $const0.46 = const(float, 2.0)  :: pyobject
                        #   $0.47 = $0.45 /? $const0.46  :: pyobject
                        #   del $const0.46
                        #   del $0.45
                        #   $0.48 = call $0.42($0.47)  :: pyobject
                        #   del $0.47
                        #   del $0.42
                        #   $const0.49 = const(int, 2)  :: pyobject
                        #   $0.50 = $0.48 ** $const0.49  :: pyobject
                        #   del $const0.49
                        #   del $0.48
                        #   $0.51 = $0.40 * $0.50  :: pyobject
                        #   del $0.50
                        #   del $0.40
                        #   $0.52 = $0.31 + $0.51  :: pyobject
                        #   del $0.51
                        #   del $0.31
                        #   $0.53 = call $0.21($0.52)  :: pyobject
                        #   del $0.52
                        #   del $0.21
                        #   $0.54 = call $0.19($0.53)  :: pyobject
                        #   del $0.53
                        #   del $0.19
                        #   $0.55 = $const0.17 * $0.54  :: pyobject
                        #   del $const0.17
                        #   del $0.54
                        #   $0.56 = cast(value=$0.55)  :: pyobject
                        #   del $0.55
                        #   return $0.56

                        * np.sin((toLons - fromLons)/2.0) ** 2)))


================================================================================

distance2() types:
 None
```

**Comment by sklam** [comment]
I can confirm the bug to be a internal compiler error.

**Comment by sklam** [comment]
problem is due to array expression rewrite

**Comment by seibert** [comment]
PR #1382 was merged, which should fix this issue.

**Comment by WeatherGod** [comment]
Just tried out the latest release of numba, and I think this problem still exists. Looking at the test that was added, I don't see how it could catch this sort of problem

What is even more fun now is that running the original script posted earlier produces an exception while calling `distance2.inspect_types()` (exception is `KeyError: 'fromLons_1'`). So, I commented out the both calls to `distance` and commented the first call to `distance2` and uncommented its 2nd call. Here is the partial output for `distance2.inspect_types()` 
```
distance2 (array(float64, 2d, A), array(float64, 2d, A), float64, float64)
--------------------------------------------------------------------------------
# File: numbatest.py
# --- LINE 24 --- 

@jit

# --- LINE 25 --- 

def distance2(fromLons, fromLats, toLons, toLats):

    # --- LINE 26 --- 
    # label 0
    #   fromLons = arg(0, name=fromLons)  :: pyobject
    #   fromLats = arg(1, name=fromLats)  :: pyobject
    #   toLons = arg(2, name=toLons)  :: pyobject
    #   toLats = arg(3, name=toLats)  :: pyobject
    #   $0.1 = global(np: <module 'numpy' from '/home/broot/scratch/miniconda/lib/python2.7/site-packages/numpy/__init__.pyc'>)  :: pyobject
    #   $0.2 = getattr(attr=radians, value=$0.1)  :: pyobject
    #   del $0.1
    #   $0.4 = call $0.2(fromLons)  :: pyobject
    #   del fromLons
    #   del $0.2
    #   fromLons.1 = $0.4  :: pyobject
    #   del $0.4
```
As you can see, the assignment still results in a `pyobject` type. When explicitly setting `nopython=True`, one gets an exception: `NotImplementedError: Don't know how to create implicit output array with 'A' layout.`. Given that there are some other issues going on, I am not ready to simply hang this problem up as a NotImplementedError. A Haversine distance calculation should not be all that hard to numba-ize.

**Comment by WeatherGod** [comment]
Note, I have opened issues #1466 and #1467 on some of the related issues in case they are orthogonal.

**Comment by WeatherGod** [comment]
I wonder if my problem is fixed by #1421? Is there a conda channel that I can use to test against?

**Comment by seibert** [comment]
Yes:
```
conda install -c numba numba
```

**Comment by WeatherGod** [comment]
Ok, so it might be fixed by #1421, but I can't know for certain because now I get the issue mentioned in #1466, which prevents me from calling inspect_types().
