### ISSUE TITLE
Speed difference between using math.* and numpy.* functions inside a jitted function

### ISSUE THREAD

**Issue by williamjshipman** [numba/numba#1616]
I did a comparison of 26 functions from these packages, and found that there are several cases where the difference is quite large. Here's the mailing list conversion where I first asked about this: [https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/zto-dKXat1w/hbQSYYn1BgAJ](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/zto-dKXat1w/hbQSYYn1BgAJ)

Here's the code to reproduce the issue: [https://bitbucket.org/williamjshipman/pythonlearning/src/b27b2d51e458b31b92d10dffbb06636c62d6d04e/NumPyFuncsSpeedInNumba/?at=master](https://bitbucket.org/williamjshipman/pythonlearning/src/b27b2d51e458b31b92d10dffbb06636c62d6d04e/NumPyFuncsSpeedInNumba/?at=master)

I've included my output, including the generated assembler code, in the output folder. It seems that most of the speed differences come from functions being "inlined". The mailing list suggestion is that whether numpy.* or math.* gets used, what LLVM IR finally gets produced should be the same so that there are no speed differences. Preferably the fastest and most reliable implementation should be used.

**Comment by seibert** [comment]
We should compare this list to #1609 to see if there are any we missed.

**Comment by pitrou** [comment]
Looking at the HTML table in `output`, the major issues should have been fixed by #1609. There may still be differences depending on the platform and compiler (for example, gcc seems better at vectorizing `sqrt` than LLVM here).

**Comment by williamjshipman** [comment]
Sorry for the quiet - had to stop playing and do some work. Now that I'm
back, I took a look through my HTML results. Here's functions not on the
list of changes for #1609 that still show a largish speed difference:

   1. expm1: math.expm1 is 1.8 times faster than numpy.expm1.
   2. atanh: numpy.arctanh is 1.6 times faster than math.atanh.
   3. log1p: math.log1p is 1.3 times faster than numpy.log1p.

In all cases, the difference between the assembler code for each is just
the use of the platform's function vs. the npymath.* version.

**Comment by seibert** [comment]
OK, thanks for the follow up.  Those are trickier functions to choose between (being transcendental functions), but we should be able to decide between one or the other.

**Comment by williamjshipman** [comment]
Thanks for the Numba 0.23 release. I've re-run my code and uploaded new results to my repository (output-2016-01-16 folder). Thanks for the improvements. There's actually been an achievement with numpy.trunc - it is now faster than math.trunc. Looking at the assembler code, both cases result in inlining, but there are three extra instructions in the math.trunc version that don't appear in the numpy.trunc version. The math.trunc version of the assembler code hasn't changed with the update to numba 0.23. Correct me if I'm wrong, it seems those extra instructions are a typecast to integer? That makes sense though as math.trunc is supposed to return an int while numpy.trunc doesn't - congrats on picking up on that little difference.

**Comment by pitrou** [comment]
> Correct me if I'm wrong, it seems those extra instructions are a typecast to integer? That makes sense though as math.trunc is supposed to return an int while numpy.trunc doesn't - congrats on picking up on that little difference.

Well spotted indeed, it's exactly that.

Thank you for running these tests! We'll examine the expm1(), atanh() and log1p() discrepancies soon. Hopefully we can just use the faster implementation everywhere.

**Comment by pitrou** [comment]
I can't find any significant difference on expm1(), atanh() and log1p() here.
Which platform are you using?

**Comment by williamjshipman** [comment]
I tested on Windows 7 using Anaconda 2.4.1 64-bit version. If it helps, the
CPU is a Core i7-2600k.

**Comment by williamjshipman** [comment]
I've just re-run the test on my Linux laptop (Anaconda 2.4.1 64-bit, Python
3.5, Intel Core2 Duo). Now I also see expm1(), atanh() and log1p() taking
the same time whether its math.* or numpy.*. This is also with Numba
0.23.1, while my previous test was with version 0.23.0. The NymPy version
on my laptop is 1.10.2, while 1.10.1 was used for the previous test.

I'll upgrade each package individually and re-run the test each time on my
Windows machine (hopefully tomorrow) to see if the version differences make
a difference.

**Comment by williamjshipman** [comment]
I've upgraded to Numba 0.23.1 on my Windows PC, and also created a Python 3.5 environment for testing. I've re-run my tests in both Python 2.7 and 3.5 on Windows 7 64-bit. Here's the results;

- Windows 7, Python 2.7.11: [https://bitbucket.org/williamjshipman/pythonlearning/src/108ee7979204/NumPyFuncsSpeedInNumba/output-2016-01-24-py27-win7/?at=master](https://bitbucket.org/williamjshipman/pythonlearning/src/108ee7979204/NumPyFuncsSpeedInNumba/output-2016-01-24-py27-win7/?at=master)
- Windows 7, Python 3.5.1: [https://bitbucket.org/williamjshipman/pythonlearning/src/108ee7979204/NumPyFuncsSpeedInNumba/output-2016-01-24-py35-win7/?at=master](https://bitbucket.org/williamjshipman/pythonlearning/src/108ee7979204/NumPyFuncsSpeedInNumba/output-2016-01-24-py35-win7/?at=master)
- Linux, Python 3.51: [https://bitbucket.org/williamjshipman/pythonlearning/src/108ee7979204/NumPyFuncsSpeedInNumba/output-2016-01-23-py3k-linux/?at=master](https://bitbucket.org/williamjshipman/pythonlearning/src/108ee7979204/NumPyFuncsSpeedInNumba/output-2016-01-23-py3k-linux/?at=master)

Plots of the speed ups (or slow downs) are included in each folder I linked to. Unfortunately, the results vary by OS. Linux with Python 3.5.1 shows most functions are equally fast whether numpy.* or math.* are used. On Windows though, the speed difference still exists for expm1(), atanh() and log1p(). Hopefully the assembler code included in those results folders can help you.

**Comment by pitrou** [comment]
Ok, so what happens is that Windows traditionally doesn't support recent math (C99) functions such expm1(), etc., so both Numpy and Python ship their own implementations. These implementations don't necessarily have the same performance behaviour, for example here is Python's expm1():
```
double
_Py_expm1(double x)
{
    /* For abs(x) >= log(2), it's safe to evaluate exp(x) - 1 directly; this
       also works fine for infinities and nans.

       For smaller x, we can use a method due to Kahan that achieves close to
       full accuracy.
    */

    if (fabs(x) < 0.7) {
        double u;
        u = exp(x);
        if (u == 1.0)
            return x;
        else
            return (u - 1.0) * x / log(u);
    }
    else
        return exp(x) - 1.0;
}
```

and here is Numpy's expm1():
```
double npy_expm1(double x)
{
    if (npy_isinf(x) && x > 0) {
        return x;
    }
    else {
        const double u = npy_exp(x);

        if (u == 1.0) {
            return x;
        } else if (u - 1.0 == -1.0) {
            return -1;
        } else {
            return (u - 1.0) * x/npy_log(u);
        }
    }
}
```

(Numpy may also be using Windows' expm1() on recent versions of Windows... I don't know Numpy's build system very much)

**Comment by williamjshipman** [comment]
Lol, I didn't know C99 was so "recent" that Windows hadn't caught up. I suggest leaving the functions as is in these cases, otherwise users could start seeing numerical differences if they operate close to whatever the limits of these functions are accurate at. Feel free to close this issue if no further work will be done on it, I feel the initial problem has bee fixed as well as it can be without making results from the numba jit functions differ from their Python versions.

**Comment by albop** [comment]
In the same spirit, by comparing performances with Julia, I found out that using `cffi+libm` is faster than  `math.` for `erfc` (https://gist.github.com/albop/879e08372054ce6ce606).  This maybe true for other functions in `libm`

**Comment by albop** [comment]
Sorry, I should at least have appended the timings for this test:
```
cpython: 2.5553548336029053
libm: 0.09564900398254395
```

**Comment by pitrou** [comment]
I can reproduce the timings under Linux. The difference is impressive, we should probably use the libm erfc() when available. Currently, we use the erfc() implementation from CPython.

**Comment by seibert** [comment]
Is there any reason for the CPython version, beyond portability?

**Comment by pitrou** [comment]
No (let's hope all platform versions are correct :-)).

**Comment by seibert** [comment]
We do have the advantage in Numba of only supporting fairly recent platforms, so I'm OK with trusting libm.  (No AIX, DEC Alpha, or SPARC for us...)

**Comment by pitrou** [comment]
We still have to fall back on the CPython version for MSVC < 2013 :-)
