### ISSUE TITLE
2D min stencil fails with AttributeError

### ISSUE THREAD

**Issue by stefanv** [numba/numba#2603]
I am trying to implement a 2D 3x3 `min` stencil.  I have the following:

```python
from numba import stencil

@stencil(neighborhood=((-1, 1), (-1, 1)))
def kernel1(a):
    mval = -np.inf
    for i in range(-1, 1):
        for j in range(-1, 1):
            if a[i, j] < mval:
                mval = a[i, j]
    return mval
```

When running the above on

```
kernel1(np.array([[1,2,3], [4,5,6], [7,8,9]]))
```

I see the following error:

```
AttributeError: 'SetItem' object has no attribute 'get_targets'
```

<details>

```python

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-95489a051be1> in <module>()
----> 1 kernel1(np.array([[1,2,3], [4,5,6], [7,8,9]]))

~/envs/py36/lib/python3.6/site-packages/numba/stencil.py in __call__(self, *args, **kwargs)
    682         (real_ret, typemap, calltypes) = self.get_return_type(array_types)
    683         new_func = self._stencil_wrapper(result, None, real_ret, typemap,
--> 684                                          calltypes, *array_types_full)
    685 
    686         if result is None:

~/envs/py36/lib/python3.6/site-packages/numba/stencil.py in _stencil_wrapper(self, result, sigret, return_type, typemap, calltypes, *args)
    632             break
    633 
--> 634         stencil_ir.blocks = ir_utils.rename_labels(stencil_ir.blocks)
    635         ir_utils.remove_dels(stencil_ir.blocks)
    636 

~/envs/py36/lib/python3.6/site-packages/numba/ir_utils.py in rename_labels(blocks)
   1032     lowering requires this order.
   1033     """
-> 1034     topo_order = find_topo_order(blocks)
   1035 
   1036     # make a block with return last if available (just for readability)

~/envs/py36/lib/python3.6/site-packages/numba/ir_utils.py in find_topo_order(blocks, cfg)
    925     """
    926     if cfg == None:
--> 927         cfg = compute_cfg_from_blocks(blocks)
    928     post_order = []
    929     seen = set()

~/envs/py36/lib/python3.6/site-packages/numba/analysis.py in compute_cfg_from_blocks(blocks)
    210     for k, b in blocks.items():
    211         term = b.terminator
--> 212         for target in term.get_targets():
    213             cfg.add_edge(k, target)
    214 

```

</details>

**Comment by stuartarchibald** [comment]
Thanks for the report and for trying this out so early! I can reproduce, pretty sure this is a bug.

As an aside, in the code above, I think the loop ranges in the kernel need adjusting as the `range(-1, 1)` doesn't span the declared neighborhood (`range(-1, 2)` does)? This doesn't however impact the problem.

Seems like the `CFG` computation is failing under the standard `@stencil` decorator, I expect it is the `if` that is causing it, this also triggers with `a = np.arange(12)`:
```python
@stencil(neighborhood=((0, 5),))
def kernel2(a):
    x = 0
    for i in range(6):
        if a[i]:
            x = 1
    return x
```
running the above `kernel2` inside an `@njit(parallel=True)` also fails with 
```python
  File "<path>/numba/numba/stencilparfor.py", line 159, in _mk_stencil_parfor
    assert isinstance(return_node, ir.Return)
AssertionError: Failed at nopython (convert to parfors)
```
Ping @DrTodd13 @ehsantn @ninegua, please could you take a look, thanks.

**Comment by DrTodd13** [comment]
Fixed Python and njit modes.  Working on parallel=True.

**Comment by DrTodd13** [comment]
9ce3b44..25009a2 fixes this issue for Python, njit, njit(parallel=True).

The issue here was where was the return statement.  There were some places assuming it was in the highest numbered block but that isn't always the case and brought up the issue of what if there were multiple return statements.  Obviously, they couldn't all be in the last block so that is the more general issue.  That issue is fixed in the above implementations but this tells fails for pyStencil.  @stuartarchibald  please have a look at that.

**Comment by stuartarchibald** [comment]
Thanks for the fixes/PR @DrTodd13 I think I assumed something similar so will go and patch up. I also note that kernels that return optionals and kernels that return `None` cause slightly confusing errors (they are caught, its just that the error message doesn't describe the root cause).

**Comment by stuartarchibald** [comment]
@stefanv this should be fixed in https://github.com/numba/numba/pull/2605 thanks.

**Comment by stefanv** [comment]
I just tried this with the latest master, and it still doesn't seem to work:

<details>
```
In [20]: x = np.arange(100, dtype=float).reshape((10, 10))

In [21]: kernel1(x)
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-21-3154f345b075> in <module>()
----> 1 kernel1(x)

~/src/numba/numba/stencil.py in __call__(self, *args, **kwargs)
    696             print("__call__", array_types, args, kwargs)
    697 
--> 698         (real_ret, typemap, calltypes) = self.get_return_type(array_types)
    699         new_func = self._stencil_wrapper(result, None, real_ret, typemap,
    700                                          calltypes, *array_types_full)

~/src/numba/numba/stencil.py in get_return_type(self, argtys)
    286                 argtys,
    287                 None,
--> 288                 {})
    289         if isinstance(return_type, types.npytypes.Array):
    290             raise ValueError(

~/src/numba/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
    865             infer.seed_type(k, v)
    866 
--> 867         infer.build_constraint()
    868         infer.propagate()
    869         typemap, restype, calltypes = infer.unify()

~/src/numba/numba/typeinfer.py in build_constraint(self)
    798         for blk in utils.itervalues(self.blocks):
    799             for inst in blk.body:
--> 800                 self.constrain_statement(inst)
    801 
    802     def return_types_from_partial(self):

~/src/numba/numba/typeinfer.py in constrain_statement(self, inst)
    957     def constrain_statement(self, inst):
    958         if isinstance(inst, ir.Assign):
--> 959             self.typeof_assign(inst)
    960         elif isinstance(inst, ir.SetItem):
    961             self.typeof_setitem(inst)

~/src/numba/numba/typeinfer.py in typeof_assign(self, inst)
   1019                                               src=value.name, loc=inst.loc))
   1020         elif isinstance(value, (ir.Global, ir.FreeVar)):
-> 1021             self.typeof_global(inst, inst.target, value)
   1022         elif isinstance(value, ir.Arg):
   1023             self.typeof_arg(inst, inst.target, value)

~/src/numba/numba/typeinfer.py in typeof_global(self, inst, target, gvar)
   1115     def typeof_global(self, inst, target, gvar):
   1116         try:
-> 1117             typ = self.resolve_value_type(inst, gvar.value)
   1118         except TypingError as e:
   1119             if (gvar.name == self.func_id.func_name

~/src/numba/numba/typeinfer.py in resolve_value_type(self, inst, val)
   1038         except ValueError as e:
   1039             msg = str(e)
-> 1040         raise TypingError(msg, loc=inst.loc)
   1041 
   1042     def typeof_arg(self, inst, target, arg):

TypingError: Untyped global name 'np': cannot determine Numba type of <class 'object'>
File "<ipython-input-1-c9ec169cb47b>", line 5
```
</details>

**Comment by stuartarchibald** [comment]
@stefanv Thanks for coming back to this and retrying. I'm afraid I can't seem to replicate what you are seeing.

```bash
$ git show|grep commit
commit 9ed665ea67ce293b94c641aab0387fc846588b38
```
```python
$ ipython
Python 3.6.3 |Anaconda, Inc.| (default, Oct 27 2017, 19:41:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from numba import stencil

In [2]: import numba as nb

In [3]: import numpy as np

In [4]: @stencil(neighborhood=((-1, 1), (-1, 1)))
   ...: def kernel1(a):
   ...:     mval = -np.inf
   ...:     for i in range(-1, 1):
   ...:         for j in range(-1, 1):
   ...:             if a[i, j] < mval:
   ...:                 mval = a[i, j]
   ...:     return mval
   ...: 

In [5]: x = np.arange(100, dtype=float).reshape((10, 10))

In [6]: kernel1(x)
Out[6]: 
array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

```

Also seems fine under 2.7:
```python
$ ipython
Python 2.7.14 |Anaconda, Inc.| (default, Nov 20 2017, 18:04:19) 
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from numba import stencil

In [2]: import numba as nb

In [3]: import numpy as np

In [4]: @stencil(neighborhood=((-1, 1), (-1, 1)))
   ...: def kernel1(a):
   ...:     mval = -np.inf
   ...:     for i in range(-1, 1):
   ...:         for j in range(-1, 1):
   ...:             if a[i, j] < mval:
   ...:                 mval = a[i, j]
   ...:     return mval
   ...: 

In [5]: x = np.arange(100, dtype=float).reshape((10, 10))

In [6]: kernel1(x)
Out[6]: 
array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [7]: nb.__version__
Out[7]: '0.36.0.dev+410.g9ed665e'
```

I guess the `<` ought to be a `>` too else `mval` will just get set to `-np.inf`?

**Comment by stefanv** [comment]
Sorry for the noise; it does work and I'm not quite sure how I managed to break it before.

**Comment by stuartarchibald** [comment]
Great, thanks for confirming. Any further issues please feel free to open another ticket.
