### ISSUE TITLE
jitclass method not inlined

### ISSUE THREAD

**Issue by sklam** [numba/numba#3305]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

From mailing-list discussion at https://groups.google.com/a/continuum.io/d/msgid/numba-users/bd1f6d06-8a71-43a1-8c60-8260f32742fc%40continuum.io?utm_medium=email&utm_source=footer

Jitclass methods are missing inter-procedural optimization (IPO) because their LLVM libraries are not being merged.  Methods are not included in IPO and can result in 2x speed difference as shown in the notebook below:

See details in notebook https://gist.github.com/sklam/8920c81707494f3f657488c24ffd9294

**Comment by sklam** [comment]
I am calling this a performance bug as it greatly impact the usefulness of jitclass.

**Comment by mbargull** [comment]
gh-2166 has been fixed in gh-3531. I haven't checked, but I assume this one is fixed, too.

**Comment by njriasan** [comment]
@sklam I reran the notebook on 0.54.1 and it seems like this is still an issue (performance difference between the two runs seems similar when I ran it). However, I'm not sure what to look at in the IR to verify this. Could you point me to a reference I can read to understand this (I can't access the google link) or elaborate on your notebook example?

**Comment by sklam** [comment]
@njriasan, on my machine, i am seeing consistent result. The thing to look for in the IR is whether the methods (e.g. `self.get`) is inlined. If it is fully inlined, both functions should be identical. 

(I also cannot access the google link. the google group is disabled)

**Comment by sklam** [comment]
I found an alternative link to it: https://groups.google.com/a/anaconda.com/g/numba-users/c/5VGYbuNUCUI/m/ePcg6ExIBAAJ?utm_medium=email&utm_source=footer
