### ISSUE TITLE
Error in using ncpdq

### ISSUE THREAD

**Issue by ShraddhaGupta28** [numba/numba#4812]
```
(indices_env) C:\Users\gupta\Downloads>process_climate_indices --index spi --periodicity monthly --netcdf_precip era5precip.nc --var_name_precip tp --output_file_base era5_precip --scales 6 12 --calibration_start_year 1979 --calibration_end_year 2019 --multiprocessing all
Error in calling operator ncpdq with:
>>> C:\Users\gupta\AppData\Local\Continuum\anaconda3\envs\indices_env\Library\bin\ncpdq -a lat,lon,time -O --output=C:\Users\gupta\AppData\Local\Temp\ncpdq_era5precip.nc3lrwfyq7.tmp era5precip.nc <<<
Inputs: era5precip.nc
b'Access is denied.\r\n'
2019-11-08  15:44:28 ERROR Failed to complete
Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1670, in main
    arguments.var_name_precip)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1539, in _prepare_file
    options=[f'-a "{dims}"', "-O"])
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\nco\nco.py", line 342, in get
    raise NCOException(**retvals)
nco.nco.NCOException: (returncode:1) b'Access is denied.\r\n'
Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gupta\AppData\Local\Continuum\anaconda3\Scripts\process_climate_indices.exe\__main__.py", line 9, in <module>
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1670, in main
    arguments.var_name_precip)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1539, in _prepare_file
    options=[f'-a "{dims}"', "-O"])
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\nco\nco.py", line 342, in get
    raise NCOException(**retvals)
nco.nco.NCOException: (returncode:1) b'Access is denied.\r\n'
```

**Comment by esc** [comment]
@ShraddhaGupta28 thanks for submitting this. May I kindly ask why you have submitted this to the Numba issue tracker? It does not appear to be a Numba issue, or did I miss something?

**Comment by ShraddhaGupta28** [comment]
I am sorry I did not update on the problem. This error with ncpdq could be removed by using ncpdq -a lat, lon, time directly on the file and then running the code with the modified file, but the next error thrown was due to numba as I paste below:

(indices_env) C:\Users\gupta\Downloads>process_climate_indices --index spi --periodicity monthly --netcdf_precip nclimgrid_lowres_prcp.nc --var_name_precip prcp --output_file_base /ESR/era5_precip --scales 6 12 --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all
2019-11-11  10:08:23 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\errors.py", line 661, in new_error_context
    yield
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\pylowering.py", line 176, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x00000273BA2CC5C0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1343, in _apply_along_axis
    parameters=args)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numpy\lib\shape_base.py", line 403, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1123, in _spi
    periodicity=parameters["periodicity"])
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py", line 26, in fit
    lmoments = _estimate_lmoments(timeseries)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 370, in _compile_for_args
    raise e
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 463, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 435, in frontend_looplift
    lifted=tuple(loops), lifted_from=None)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 1017, in compile_ir
    lifted_from=lifted_from)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 385, in compile_ir
    return self._compile_ir()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 893, in _compile_ir
    return self._compile_core()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 711, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 659, in backend_object_mode
    self.flags)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 1148, in py_lowering_stage
    lower.lower()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\errors.py", line 669, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
[1m[1m(<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x00000273BA2CC5C0>)
[1m
File "..\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py", line 143:[0m
[1mdef _estimate_lmoments(values: np.ndarray) -> np.ndarray:
    <source elided>
        _logger.warning(message)
[1m        raise ValueError(message)
[0m        [1m^[0m[0m
[0m
[0m[1m[1] During: lowering "raise <class 'ValueError'>('Insufficient number of values to perform sample L-moments estimation')" at c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py (143)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!


"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1689, in main
    _compute_write_index(kwrgs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1021, in _compute_write_index
    args=args)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1303, in _parallel_process
    pool.map(_apply_along_axis, chunk_params)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
numba.errors.LoweringError: [1mFailed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
[1m[1m(<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x00000273BA2CC5C0>)
[1m
File "..\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py", line 143:[0m
[1mdef _estimate_lmoments(values: np.ndarray) -> np.ndarray:
    <source elided>
        _logger.warning(message)
[1m        raise ValueError(message)
[0m        [1m^[0m[0m
[0m
[0m[1m[1] During: lowering "raise <class 'ValueError'>('Insufficient number of values to perform sample L-moments estimation')" at c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py (143)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

[0m
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\errors.py", line 661, in new_error_context
    yield
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\pylowering.py", line 176, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x00000273BA2CC5C0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1343, in _apply_along_axis
    parameters=args)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numpy\lib\shape_base.py", line 403, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1123, in _spi
    periodicity=parameters["periodicity"])
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py", line 26, in fit
    lmoments = _estimate_lmoments(timeseries)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 370, in _compile_for_args
    raise e
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 463, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 435, in frontend_looplift
    lifted=tuple(loops), lifted_from=None)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 1017, in compile_ir
    lifted_from=lifted_from)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 385, in compile_ir
    return self._compile_ir()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 893, in _compile_ir
    return self._compile_core()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 711, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 659, in backend_object_mode
    self.flags)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\compiler.py", line 1148, in py_lowering_stage
    lower.lower()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\errors.py", line 669, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
[1m[1m(<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x00000273BA2CC5C0>)
[1m
File "..\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py", line 143:[0m
[1mdef _estimate_lmoments(values: np.ndarray) -> np.ndarray:
    <source elided>
        _logger.warning(message)
[1m        raise ValueError(message)
[0m        [1m^[0m[0m
[0m
[0m[1m[1] During: lowering "raise <class 'ValueError'>('Insufficient number of values to perform sample L-moments estimation')" at c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py (143)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!


"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gupta\AppData\Local\Continuum\anaconda3\Scripts\process_climate_indices.exe\__main__.py", line 9, in <module>
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1689, in main
    _compute_write_index(kwrgs)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1021, in _compute_write_index
    args=args)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\__main__.py", line 1303, in _parallel_process
    pool.map(_apply_along_axis, chunk_params)
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\users\gupta\appdata\local\continuum\anaconda3\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
numba.errors.LoweringError: [1mFailed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
[1m[1m(<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x00000273BA2CC5C0>)
[1m
File "..\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py", line 143:[0m
[1mdef _estimate_lmoments(values: np.ndarray) -> np.ndarray:
    <source elided>
        _logger.warning(message)
[1m        raise ValueError(message)
[0m        [1m^[0m[0m
[0m
[0m[1m[1] During: lowering "raise <class 'ValueError'>('Insufficient number of values to perform sample L-moments estimation')" at c:\users\gupta\appdata\local\continuum\anaconda3\lib\site-packages\climate_indices\lmoments.py (143)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

[0m

**Comment by ShraddhaGupta28** [comment]
I would like to add that the above check I did with the file mentioned in
[climate-indices.pdf](https://github.com/numba/numba/files/3830551/climate-indices.pdf), to see whether the problem is actually related to how data is arranged on the file or its something related to the package.
Thanks !

**Comment by esc** [comment]
@ShraddhaGupta28 thanks for adding the exception trace. Can you tell us where `process_climate_indices` comes from? I'd like to try to reproduce this on my machine.

**Comment by stuartarchibald** [comment]
I suspect that this issue was fixed a couple of versions back (`NotImplementedError: (<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x00000273BA2CC5C0>)` issue was fixed in https://github.com/numba/numba/pull/4224). @ShraddhaGupta28 please could you report the Numba version in use and also try updating to version 0.46 to see if that fixes it? Thanks.

**Comment by ShraddhaGupta28** [comment]
I checked my Numba version, and it is 0.46, but that doesn't fix it.

**Comment by stuartarchibald** [comment]
@ShraddhaGupta28 I'm not sure you are on 0.46 for the above error message because in 0.46 a line was added to all `LoweringError` message strings that contains the version. i.e. the above would show:
```
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```
Does your upgraded? version have that line in the error message?

**Comment by ShraddhaGupta28** [comment]
![image](https://user-images.githubusercontent.com/55398997/68706873-f27e1480-0590-11ea-85d0-2e10cae76968.png)
As you see in the image, the environment in which I am running the code has numba version 0.46.0

The error shown is slightly different:

This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by stuartarchibald** [comment]
That the error message is different to that which is in Numba 0.46 suggests that, unless I'm mistaken, the `ncpdq` package is not actually running with 0.46. This is the specific part of the code that generates the message (from the 0.46 release branch):
https://github.com/numba/numba/blob/release0.46/numba/errors.py#L351-L356

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
