### ISSUE TITLE
structs not supported for jitclass

### ISSUE THREAD

**Issue by xor2k** [numba/numba#4814]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I tried to use jitclass with struct types, as imported from numpy. However, it yields a long error message. Here is some demo code to reproduce:

```
import numpy as np

from numba import jitclass, types
from numba.numpy_support import from_dtype

names_and_offsets_dtype = np.dtype([ \
    ('field1', np.uint64), \
    ('field2', np.uint64)])

spec = [
    ('attr1', types.unicode_type),
    ('attr2', from_dtype(np.uint64)),
    ('attr3', from_dtype(names_and_offsets_dtype))
]

@jitclass(spec)
class demo():
    def __init__(self):
        print("yay")

tmp = demo()
```
When the line with attr3 is removed, the code does not yield an error.

**Comment by esc** [comment]
@xor2k thanks for submitting this issue to the Numba issue tracker. For reference, here is the error message the example yields:

```
💥 zsh» python foo/foo62.py
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/errors.py", line 717, in new_error_context
    yield
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 467, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 1030, in lower_expr
    res = impl(self.context, self.builder, ty, val, expr.attr)
  File "/Users/vhaenel/git/numba/numba/targets/imputils.py", line 149, in res
    return real_impl(context, builder, typ, value, attr)
  File "/Users/vhaenel/git/numba/numba/jitclass/base.py", line 405, in get_attr_impl
    getattr(data, _mangle_attr(attr)))
  File "/Users/vhaenel/git/numba/numba/cgutils.py", line 155, in __getattr__
    return self[self._datamodel.get_field_position(field)]
  File "/Users/vhaenel/git/numba/numba/cgutils.py", line 172, in __getitem__
    return self._cast_member_to_value(index, member_val)
  File "/Users/vhaenel/git/numba/numba/cgutils.py", line 248, in _cast_member_to_value
    return model.from_data(self._builder, val)
  File "/Users/vhaenel/git/numba/numba/datamodel/models.py", line 936, in from_data
    raise NotImplementedError("use load_from_data_pointer() instead")
NotImplementedError: use load_from_data_pointer() instead

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo/foo62.py", line 21, in <module>
    tmp = demo()
  File "/Users/vhaenel/git/numba/numba/jitclass/base.py", line 126, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 535, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 328, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 387, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 367, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 358, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 328, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 390, in run_pass
    NativeLowering().run_pass(state) # TODO: Pull this out into the pipeline
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 335, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 273, in create_cpython_wrapper
    release_gil=release_gil)
  File "/Users/vhaenel/git/numba/numba/targets/cpu.py", line 162, in create_cpython_wrapper
    builder.build()
  File "/Users/vhaenel/git/numba/numba/callwrapper.py", line 124, in build
    self.build_wrapper(api, builder, closure, args, kws)
  File "/Users/vhaenel/git/numba/numba/callwrapper.py", line 178, in build_wrapper
    obj = api.from_native_return(retty, retval, env_manager)
  File "/Users/vhaenel/git/numba/numba/pythonapi.py", line 1431, in from_native_return
    out = self.from_native_value(typ, val, env_manager)
  File "/Users/vhaenel/git/numba/numba/pythonapi.py", line 1445, in from_native_value
    return impl(typ, val, c)
  File "/Users/vhaenel/git/numba/numba/jitclass/boxing.py", line 136, in _box_class_instance
    box_subclassed = _specialize_box(typ)
  File "/Users/vhaenel/git/numba/numba/jitclass/boxing.py", line 119, in _specialize_box
    fast_fget = fget.compile((typ,))
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 535, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 328, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 387, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 367, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 358, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 328, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 390, in run_pass
    NativeLowering().run_pass(state) # TODO: Pull this out into the pipeline
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 333, in run_pass
    lower.lower()
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 220, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 245, in lower_function_body
    self.lower_block(block)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/Users/vhaenel/miniconda3/envs/new-numba/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/vhaenel/git/numba/numba/errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/vhaenel/git/numba/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
  File "/Users/vhaenel/git/numba/numba/errors.py", line 717, in new_error_context
    yield
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 467, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 1030, in lower_expr
    res = impl(self.context, self.builder, ty, val, expr.attr)
  File "/Users/vhaenel/git/numba/numba/targets/imputils.py", line 149, in res
    return real_impl(context, builder, typ, value, attr)
  File "/Users/vhaenel/git/numba/numba/jitclass/base.py", line 405, in get_attr_impl
    getattr(data, _mangle_attr(attr)))
  File "/Users/vhaenel/git/numba/numba/cgutils.py", line 155, in __getattr__
    return self[self._datamodel.get_field_position(field)]
  File "/Users/vhaenel/git/numba/numba/cgutils.py", line 172, in __getitem__
    return self._cast_member_to_value(index, member_val)
  File "/Users/vhaenel/git/numba/numba/cgutils.py", line 248, in _cast_member_to_value
    return model.from_data(self._builder, val)
  File "/Users/vhaenel/git/numba/numba/datamodel/models.py", line 936, in from_data
    raise NotImplementedError("use load_from_data_pointer() instead")
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)
use load_from_data_pointer() instead

File "<string>", line 3:
<source missing, REPL/exec in use?>

[1] During: lowering "$0.2 = getattr(value=__numba_self_, attr=attr3)" at <string> (3)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a bug/not implemented yet.

**Comment by marnixhoh** [comment]
I am running into the same issue. Does there happen to be a timeline for when this bug will be resolved?

Thanks! :)

**Comment by marnixhoh** [comment]
Hi this appears to have been solved: see #5798

**Comment by stuartarchibald** [comment]
@marnixhoh The reported MWE still reproduces for me, does it not for you?

**Comment by marnixhoh** [comment]
Yes the MWE does, but in #5798 a solution was provided. Now, I am not sure whether this classifies as "solved" or "workaround". Here is a working example of the above:

```
import numpy as np

from numba import jitclass, types
from numba.numpy_support import from_dtype

names_and_offsets_dtype = np.dtype([ \
    ('field1', np.uint64), \
    ('field2', np.uint64)])

spec = [
    ('attr1', types.unicode_type),
    ('attr2', from_dtype(np.uint64)),
    ('attr3', from_dtype(names_and_offsets_dtype)[:])
]

@jitclass(spec)
class demo():
    def __init__(self):
        print("yay")

tmp = demo()
```

The only difference is the [:] on the 'attr3' line in the spec list

**Comment by stuartarchibald** [comment]
@marnixhoh I think the `[:]` fundamentally changes the type from a `Record` to a record array?

```pycon
In [1]: from numba.np.numpy_support import from_dtype                                                                           

In [2]: import numpy as np                                                                                                      

In [3]: names_and_offsets_dtype = np.dtype([ \ 
   ...:     ('field1', np.uint64), \ 
   ...:         ('field2', np.uint64)])                                                                                         

In [4]: from_dtype(names_and_offsets_dtype)                                                                                     
Out[4]: Record(field1[type=uint64;offset=0],field2[type=uint64;offset=8];16;False)

In [5]: from_dtype(names_and_offsets_dtype)[:]                                                                                  
Out[5]: unaligned array(Record(field1[type=uint64;offset=0],field2[type=uint64;offset=8];16;False), 1d, A)


```

**Comment by marnixhoh** [comment]
@stuartarchibald Ah I see. It does "solve" the problem though...

**Comment by stuartarchibald** [comment]
@marnixhoh errr, I'm not sure it does solve it? It seems like it demonstrates a similar case is working ok, this case being something that could potentially be used as a work around.

**Comment by marnixhoh** [comment]
@stuartarchibald Yes you are absolutely right. My earlier comment was indeed not very clear. With "solve" I meant a workaround
