### ISSUE TITLE
Serialization incompatibility between Os (Windows, MacOS, Ubuntu) when loading a trained UMAP object

### ISSUE THREAD

**Issue by konradsemsch** [numba/numba#6143]
I have a trained UMAP object (trained on MacOS), that now I'm trying to load on an Ubuntu machine. Unfortunately this is not working. I've ensured that python version as well as dependencies are the same between both environments, however, this doesn't resolve the issue. The same model object can be loaded on MacOS/ Windows - it only fails when running on Ubuntu. I've gone through a bunch of different issues but cannot trace a potential problem source.

I've also submitted an issue with UMAP ([link](https://github.com/lmcinnes/umap/issues/473)), but since serialization is working on the same OS, as well as the error points to numba, I don't think they can help me much. I have also tried using different UMAP metrics but the issue persists.

Would you have any advice on that?

**Error:**

```python
2020-08-18T12:08:11.251+02:00 | model = joblib.load(path)
-- | --
  | 2020-08-18T12:08:11.251+02:00 | File "/usr/local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 585, in load
  | 2020-08-18T12:08:11.251+02:00 | obj = _unpickle(fobj, filename, mmap_mode)
  | 2020-08-18T12:08:11.251+02:00 | File "/usr/local/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
  | 2020-08-18T12:08:11.252+02:00 | obj = unpickler.load()
  | 2020-08-18T12:08:11.252+02:00 | File "/usr/local/lib/python3.6/pickle.py", line 1050, in load
  | 2020-08-18T12:08:11.253+02:00 | dispatch[key[0]](self)
  | 2020-08-18T12:08:11.253+02:00 | File "/usr/local/lib/python3.6/pickle.py", line 1398, in load_reduce
  | 2020-08-18T12:08:11.253+02:00 | stack[-1] = func(*args)
  | 2020-08-18T12:08:11.253+02:00 | File "/usr/local/lib/python3.6/site-packages/numba/core/serialize.py", line 40, in _rebuild_reduction
  | 2020-08-18T12:08:11.254+02:00 | return cls._rebuild(*args)
  | 2020-08-18T12:08:11.254+02:00 | File "/usr/local/lib/python3.6/site-packages/numba/core/dispatcher.py", line 787, in _rebuild
  | 2020-08-18T12:08:11.254+02:00 | self = cls(py_func, locals, targetoptions, impl_kind)
  | 2020-08-18T12:08:11.254+02:00 | File "/usr/local/lib/python3.6/site-packages/numba/core/dispatcher.py", line 710, in __init__
  | 2020-08-18T12:08:11.255+02:00 | pysig = utils.pysignature(py_func)
  | 2020-08-18T12:08:11.255+02:00 | File "/usr/local/lib/python3.6/inspect.py", line 3065, in signature
  | 2020-08-18T12:08:11.256+02:00 | return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  | 2020-08-18T12:08:11.256+02:00 | File "/usr/local/lib/python3.6/inspect.py", line 2815, in from_callable
  | 2020-08-18T12:08:11.257+02:00 | follow_wrapper_chains=follow_wrapped)
  | 2020-08-18T12:08:11.257+02:00 | File "/usr/local/lib/python3.6/inspect.py", line 2193, in _signature_from_callable
  | 2020-08-18T12:08:11.258+02:00 | raise TypeError('{!r} is not a callable object'.format(obj))
  | 2020-08-18T12:08:11.258+02:00 | TypeError: ((4, b'3\r\r\n', b'\xe3\x02\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00sF\x00\x00\x00d\x01}\x02x.t\x00\|\x00j\x01d\x02\x19\x00\x83\x01D\x00]\x1c}\x03\|\x00\|\x03\x19\x00\|\x01\|\x03\x19\x00k\x03r\x14\|\x02d\x037\x00}\x02q\x14W\x00t\x02\|\x02\x83\x01\|\x00j\x01d\x02\x19\x00\x1b\x00S\x00)\x04N\xe7\x00\x00\x00\x00\x00\x00\x00\x00\xe9\x00\x00\x00\x00\xe7\x00\x00\x00\x00\x00\x00\xf0?)\x03\xda\x05range\xda\x05shape\xda\x05float)\x04\xda\x01x\xda\x01y\xda\x06result\xda\x01i\xa9\x00r\x0b\x00\x00\x00\xfay/Users/konradsemsch/.local/share/virtualenvs/pcw_signup_prediction-WNi69Rz8/lib/python3.6/site-packages/umap/distances.py\xda\x07hamming8\x01\x00\x00s\n\x00\x00\x00\x00\x02\x04\x01\x14\x01\x10\x01\x0c\x02'), {'range': <class 'range'>, 'float': <class 'float'>, '__name__': 'umap.distances'}, 'hamming', None) is not a callable object
```

**Environment**

* python 3.6.8
* dependencies:

```python
alembic==1.4.2
attrs==19.3.0
awscli==1.18.121
boto3==1.14.44
botocore==1.17.44
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
cliff==3.4.0
cmaes==0.6.0
cmd2==1.3.3
colorama==0.4.3
colorlog==4.2.1
dill==0.3.2
docutils==0.15.2
idna==2.10
importlib-metadata==1.7.0
jmespath==0.10.0
joblib==0.16.0
lightgbm==2.3.1
llvmlite==0.34.0
Mako==1.1.3
MarkupSafe==1.1.1
numba==0.51.0
numpy==1.19.1
optuna==1.5.0
pandas==1.1.0
pbr==5.4.5
pgeocode==0.2.1
prettytable==0.7.2
pyarrow==1.0.0
pyasn1==0.4.8
pyparsing==2.4.7
pyperclip==1.8.0
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
rsa==4.5
s3transfer==0.3.3
scikit-learn==0.23.1
scipy==1.5.2
six==1.15.0
SQLAlchemy==1.3.19
stevedore==3.2.0
threadpoolctl==2.1.0
tqdm==4.48.2
umap-learn==0.4.6
urllib3==1.25.10
wcwidth==0.2.5
zipp==3.1.0
```

**Comment by sklam** [comment]
@konradsemsch 

To help diagnose, I have a few questions:

- Was the UMAP object created with a different numba version?
- Do you know if it used to work with older Numba version?

The error seems to indicate an error in the deserialization. There are changes to the serialization in Numba 0.51.0 that could cause incompatibility to serialized data from older version.

**Comment by konradsemsch** [comment]
@sklam 

Unfortunately I cannot comment on that with 100% certainty, but it's likely that we might have a version mismatch (this object was created approx 3 weeks ago) and we do not have `numba` fixed on a given version (just as `umap-learn` dependency). I'll pin the `numba` version in the env tomorrow while creating the object and then also loading it to check if that might be the cause.

Let me come back to you tomorrow with further comments on this.

**Comment by esc** [comment]
@konradsemsch just following up, did you manage to uncover anything here?

**Comment by konradsemsch** [comment]
Hi! I'm back from holidays and found the time to test again. We pinned the numba and dill versions, retrained and serialized all models again and I'm happy to let you know that things are working as expected now. Thanks!

**Comment by esc** [comment]
@konradsemsch thanks for reporting back!  I will close this issue now as it has been resolved. Thank you for using Numba! 🙏

**Comment by tomasrojasc** [comment]
Hi! I have the same versions for everything and still having the same issue. In my case the problem arise when the umap object was imported from debian to arch
