### ISSUE TITLE
Error on import with numpy HEAD

### ISSUE THREAD

**Issue by max-sixty** [numba/numba#8615]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This will be a somewhat sparse bug report, but putting here early in case anyone recognizes this. We can do more work to replicate the environment if not.

In our upstream tests, xarray tests nightly against unreleased versions of our dependencies to get ahead of any incompatible code. Occasionally it also catches bugs in upstream libraries.

Here, we're getting an error importing some items from `numba.np.ufunc`, including the somewhat confusing `SystemError: initialization of _internal failed without raising an exception` at the bottom of the stack trace.

https://github.com/pydata/xarray/issues/7306

Any ideas on what might be causing this? 

Thanks in advance!

**Comment by stuartarchibald** [comment]
Thanks for the report @max-sixty. Do you know what version of Python, Numba and NumPy (and where from, e.g. `conda-forge` or `pip` or ...) were present when this a) failed and b) was last successful?

I think:
```
SystemError: initialization of _internal failed without raising an exception
```
is saying that the module failed to initialize as it returned an error code, but there was no exception raised to go with the failure result (e.g. function `PyInit_<module name>` returned `NULL` but an exception wasn't set).

**Comment by max-sixty** [comment]
Thanks for the swift response @stuartarchibald !

> Do you know what version of Python, Numba and NumPy (and where from, e.g. `conda-forge` or `pip` or ...) were present when this a) failed and b) was last successful?

Here's the full version info: https://github.com/pydata/xarray/actions/runs/3519182359/jobs/5906608476#step:8:74

Actually it seems we don't install the upstream version of numba, so this was running on `0.56.4          py310ha5257ce_0`. FYI the script we use to install dependencies is at https://github.com/pydata/xarray/blob/main/ci/install-upstream-wheels.sh.

This is the first day it's failed with this error, so it is likely to be a change somewhere in the past day.

Though I realize "somewhere" isn't that helpful, and it now seems that it may not be a numba-specific error given that hasn't changed. Do you possibly have any similar tests which run on the latest branch of `numpy` etc? If those pass, then this is more likely to be something specific to xarray / numbagg, even though that didn't look likely at first glance.

> is saying that the module failed to initialize as it returned an error code, but there was no exception raised to go with the failure result (e.g. function `PyInit_<module name>` returned `NULL` but an exception wasn't set).

Ah great, that makes much more sense.

**Comment by keewis** [comment]
> This is the first day it's failed with this error, so it is likely to be a change somewhere in the past day.

That's not quite true, it started failing 4 days ago but there was a bug in our CI which caused that to go unnoticed. Probably doesn't change too much, though.

**Comment by stuartarchibald** [comment]
> Thanks for the swift response @stuartarchibald !

No problem!

> > Do you know what version of Python, Numba and NumPy (and where from, e.g. `conda-forge` or `pip` or ...) were present when this a) failed and b) was last successful?
> 
> Here's the full version info: https://github.com/pydata/xarray/actions/runs/3519182359/jobs/5906608476#step:8:74
> 
> Actually it seems we don't install the upstream version of numba, so this was running on `0.56.4 py310ha5257ce_0`. FYI the script we use to install dependencies is at https://github.com/pydata/xarray/blob/main/ci/install-upstream-wheels.sh.
> 
> This is the first day it's failed with this error, so it is likely to be a change somewhere in the past day.
> 
> Though I realize "somewhere" isn't that helpful, and it now seems that it may not be a numba-specific error given that hasn't changed. Do you possibly have any similar tests which run on the latest branch of `numpy` etc? If those pass, then this is more likely to be something specific to xarray / numbagg, even though that didn't look likely at first glance.

Thanks for this information. Numba doesn't automatically test against NumPy latest/mainline, but it does test NumPy alphas/pre-releases and provides feedback for these. Once a NumPy package becomes more generally available across a number of distribution mechanisms, support for that release of NumPy is added to Numba. As a result, released versions of Numba have explicit version constraints with respect to packages such as NumPy. As it's quite common for updates to e.g. NumPy to break something in Numba, Numba tries really hard to provide predicable failure modes (e.g. won't install or `RuntimeError` for unsupported NumPy being found).

Do you think it'd be possible to `diff` the logs between last working and now? That might hint at the problem?

> > is saying that the module failed to initialize as it returned an error code, but there was no exception raised to go with the failure result (e.g. function `PyInit_<module name>` returned `NULL` but an exception wasn't set).
> 
> Ah great, that makes much more sense.

Great, glad that's clearer, it's quite a "low level" problem.

**Comment by stuartarchibald** [comment]
Thanks for checking @keewis. I'm going to make some guesses based on Numba internals... I think the following:
1. That the issue is unlikely to be `glibc`, `Python` or Python C-API related as to get to the point of importing `numba.np.ufunc._internal` Numba would have had to have imported other C extension modules that would have similar `glibc` linkage and C-API use and these evidently worked "OK" as errors were not raised.
2. That whilst Numba guards against using unsupported NumPy versions, current NumPy nightlies are likely to be reporting that they are 1.23 series builds as IIRC 1.24 hasn't been tagged, so Numba is effectively using something that hasn't been tested.
3. Following some discussion at the weekly triage meeting, @gmarkall noted that there's some potential for susceptibility against changes in NumPy ufunc definitions in the `init_ufunc_dispatch` function in `_internal.c`. NumPy has recently merged a change to help with #8538 which may well be the cause of the problem if 2. is also correct.

Numba relies on NumPy infrastructure for e.g. ufunc creation, and so there is a very tight coupling in this respect, between Numba and NumPy (the code is all in C and uses Python/NumPy C-API).

To debug and potentially fix the issue reported, maybe first try installing a supported released version of NumPy? If that fixes it, it narrows the problem down to what is suspected in the above.

Hope this helps.

**Comment by max-sixty** [comment]
> To debug and potentially fix the issue reported, maybe first try installing a supported released version of NumPy? If that fixes it, it narrows the problem down to what is suspected in the above.

Our tests are still very much passing on the newest released versions of libraries; so this is only an issue with the versions from HEADs. I just tried installing `numpy` from main — I get the same failure with numba 0.56.3 but it works with numba 0.56.4. I notice that's consistent with the declared dependencies of `numba`, so it seems `numba` is doing everything it should be...

Possibly over at xarray, we should at least ensure we're on the latest numba for this test. I did a PR to do that earlier: https://github.com/pydata/xarray/pull/7311#pullrequestreview-1190125481. Let us know if there's some pre-compiled version of dependencies (https://github.com/pydata/xarray/pull/7311#discussion_r1029378003), otherwise we'll just use `pip`.

Feel free to close, thanks for your attention @stuartarchibald !

**Comment by keewis** [comment]
I think you're right, I can reproduce locally with the most recent nightly `numpy` version:
```bash
# works
pip install --no-deps -i https://pypi.anaconda.org/scipy-wheels-nightly/simple --pre "numpy==1.24.0.dev0+1068.g6aacc5167"
# fails
pip install --no-deps -i https://pypi.anaconda.org/scipy-wheels-nightly/simple --pre "numpy==1.24.0.dev0+1120.gf30af6acd"
```
where the new version was uploaded ~6 days ago.

**Comment by keewis** [comment]
for me `numba=0.56.4` from `conda-forge` fails locally with `numpy=1.24.0.dev0+1120.gf30af6acd`, so not sure what I'm doing wrong? @max-sixty, was that with the `numba` head?

**Comment by max-sixty** [comment]
Redoing the test; I also get a failure with:
- both that nightly wheel command, and `pip install .` on numpy''s HEAD 
- both numba 0.56.3 and 0.56.4

So I think my prior success with 0.56.4 must have been a mistake (I notice that pip reinstalls a lower version of numpy when installing a new version of numba, so that may have been it, mea culpa)

...so I'm not sure what we should do from Xarray's POV — I guess we can try running tests without `numba`? But that misses some of the utility of these upstream tests.

**Comment by stuartarchibald** [comment]
I would anticipate that any issue, of the nature as described above, that is in 0.56.3 would also be in 0.56.4. The changes are here:
https://github.com/numba/numba/blob/3e96339a523b3cf4b737b8fff7dba6ee64927584/CHANGE_LOG#L1-L14
but in summary, it involved adding a couple of lines to fix a regression in `<array>.view()`-like capabilities on the CUDA hardware target. Something that should not in any way impact the issue above as it's all in JIT code generation and specifically for CUDA users.

**Comment by gmarkall** [comment]
The following quick-n-dirty patch gets around the `SystemError` with NumPy `main`:

```diff
diff --git a/numba/np/ufunc/_internal.c b/numba/np/ufunc/_internal.c
index 98a643788..c83b4f403 100644
--- a/numba/np/ufunc/_internal.c
+++ b/numba/np/ufunc/_internal.c
@@ -326,10 +326,13 @@ init_ufunc_dispatch(int *numpy_uses_fastcall)
             } else if (strncmp(crnt_name, "reduceat", 9) == 0) {
                 ufunc_dispatch.ufunc_reduceat =
                     (PyCFunctionWithKeywords)crnt->ml_meth;
+            } else if (strncmp(crnt_name, "resolve_dtypes", 15) == 0) {
             } else {
                 result = -1;
             }
             break;
+        case '_':
+            break;
         default:
             result = -1; /* Unknown method */
         }
```

However, I have not tried much beyond that yet!

**Comment by gmarkall** [comment]
The following is also needed because the deprecated `MachAr` is now removed:

```diff
diff --git a/numba/np/arraymath.py b/numba/np/arraymath.py
index 7f53c6563..12edd8e38 100644
--- a/numba/np/arraymath.py
+++ b/numba/np/arraymath.py
@@ -3994,7 +3994,7 @@ def _gen_np_machar():
         return impl
 
 
-_gen_np_machar()
+# _gen_np_machar()
 
 
 def generate_xinfo(np_func, container, attr):
```

with this I'm able to start running the test suite - as things pass by, everything appears OK so far, but will update here if the test run completes.

**Comment by gmarkall** [comment]
I had to cancel my test run as I was working on other things, but it looked like things were generally working with those small changes: https://github.com/gmarkall/numba/tree/np-124 (YMMV, etc!)

**Comment by max-sixty** [comment]
Thanks @stuartarchibald — that makes sense. I think we'll explore excluding anything that runs numba in these tests if this crops up again

> 2\. There are simply not the resources (human, packages, or compute) for Numba to track NumPy `HEAD`.

Totally empathize! FWIW, we've found that the upstream `HEAD` tests **reduce** the maintainer burden, since we can solve problems at a slower pace — no need to rush when there's an upstream release that breaks something — and we can provide feedback on breakages where there's a mistaken breaking change. But numba is a more technically complex project than Xarray, so possibly the learning is not transferable.

**Comment by stuartarchibald** [comment]
> Thanks @stuartarchibald — that makes sense. I think we'll explore excluding anything that runs numba in these tests if this crops up again

@max-sixty no problem, glad it was helpful.

> > 2. There are simply not the resources (human, packages, or compute) for Numba to track NumPy `HEAD`.
> 
> Totally empathize! FWIW, we've found that the upstream `HEAD` tests **reduce** the maintainer burden, since we can solve problems at a slower pace — no need to rush when there's an upstream release that breaks something — and we can provide feedback on breakages where there's a mistaken breaking change. But numba is a more technically complex project than Xarray, so possibly the learning is not transferable.

Thanks for sharing this. I can see that for some projects, aspects of the described approach would certainly be beneficial in terms of maintenance burden.

The Numba maintainers do track changes to dependencies and work with other projects if issues are anticipated, they also often "try out" the code base against newer versions of projects that impact Numba (cPython, LLVM, NumPy) etc to assess the level of effort needed to do the necessary updates. I think the learning from the Numba side is probably, that in developing a compiler, having a stable and predictable environment in which to develop makes it easier to isolate problems. This is in part due to problems often being very niche e.g. one single Python+NumPy+OS+CPU combination might exhibit a particular issue!

**Comment by larsoner** [comment]
Just a heads up that I think I'm hitting this error in CIs now that NumPy 1.24 has been released:

https://github.com/mne-tools/mne-python/actions/runs/3732610574/jobs/6332287508#step:9:56

I expect others might hit it soon, too.

**Comment by MarcoGorelli** [comment]
> I expect others might hit it soon, too.

Yup, same story in pandas https://github.com/pandas-dev/pandas/actions/runs/3737292562/jobs/6342364883 

```
________________________ ERROR collecting test session _________________________
../../../micromamba/envs/test/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../../../micromamba/envs/test/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
pandas/tests/window/conftest.py:93: in <module>
    @pytest.fixture(params=[pytest.param("numba", marks=td.skip_if_no("numba")), "cython"])
pandas/util/_test_decorators.py:192: in skip_if_no
    not safe_import(package, min_version=min_version), reason=msg
pandas/util/_test_decorators.py:95: in safe_import
    mod = __import__(mod_name)
../../../micromamba/envs/test/lib/python3.8/site-packages/numba/__init__.py:43: in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
../../../micromamba/envs/test/lib/python3.8/site-packages/numba/np/ufunc/__init__.py:3: in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
../../../micromamba/envs/test/lib/python3.8/site-packages/numba/np/ufunc/decorators.py:3: in <module>
    from numba.np.ufunc import _internal
E   SystemError: initialization of _internal failed without raising an exception
```

**Comment by gmarkall** [comment]
Looks like I forgot to mention in this issue, the PR / branch for NumPy 1.24 support is https://github.com/numba/numba/pull/8620

**Comment by fmPeretti** [comment]
Having the same issue over here with an old numpy version 😕 rolling back to an old version dindt work for me
![image](https://user-images.githubusercontent.com/35942633/210580431-7bafb1af-7ce9-4d5c-8303-a277e264fa48.png)

**Comment by Veda-73** [comment]
I was having the same problem with the librosa library (The reason was that librosa working with different versions of scipy and matplotlib), so I uninstalled numpy, matplotlib, and scipy, installed librosa first which installed its own compatible versions of libraries above and then I installed the necessary libraries. That seems to work for me.

**Comment by stuartarchibald** [comment]
Thank you all for your comments/feedback on this issue. This issue seems to have diverged a little from the originally reported problem and so I'm closing this issue as resolved with some specific follow up issues to subscribe to if they are important to you:

1. With respect to the originally posted issue, this comment https://github.com/numba/numba/issues/8615#issuecomment-1324810269 (and some discussion immediately after) explains the decisions surrounding Numba not tracking NumPy `HEAD`. 
2. With respect to the originally posted issue, #8691 is the patch for making Numba compatible with NumPy 1.24.
3. The NumPy 1.24 related problem that manifests as the error:
    ```
    SystemError: initialization of _internal failed without raising an exception
    ```
   is tracked in #8718.

**Comment by stunlocked1** [comment]
what version of numpy should i install?

**Comment by gmarkall** [comment]
> what version of numpy should i install?

If you're using the last released version of Numba (0.56.4 at time of writing), NumPy 1.18 - 1.23 are supported.

**Comment by arijin** [comment]
> for me `numba=0.56.4` from `conda-forge` fails locally with `numpy=1.24.0.dev0+1120.gf30af6acd`, so not sure what I'm doing wrong? @max-sixty, was that with the `numba` head?
> 
> Edit: the install would be
> 
> ```shell
> pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple --pre "numpy==1.24.0.dev0+1120.gf30af6acd" --upgrade
> ```
> 
> and `pip` does indeed complain that `numba` requires `numpy<1.24` but installs it anyways (as intended in this case, because we do actually want to test with the most recent version, even if that breaks something). So while point 2 from [#8615 (comment)](https://github.com/numba/numba/issues/8615#issuecomment-1323926762) does not apply, point 3 may very well be the cause of the problem.

Thanks. This help a lot. I reinstall numpy by "pip install numpy==1.23.0". Then, the error when "import numba" was solved.

**Comment by pimiento** [comment]
Is it fixed in any version?

**Comment by chiiingky** [comment]
Hello everyone, the solutions posted here did not fix the problem for me. I downgraded numpy to v1.23.0 and it did not work with both numpy 1.23.0 and 1.24.0. I installed everything with conda-forge and I am using WSL. Any help is greatly appreciated. Thank you!

**Comment by fyenne** [comment]
> Hello everyone, the solutions posted here did not fix the problem for me. I tried numba v0.56.4 and v0.56.3 and both of these versions did not work with either numpy 1.23.0 or 1.24.0. I installed everything with conda-forge and I am using WSL. Any help would be greatly appreciated. Thank you!

I fixed with  `conda install cudatoolkit` on a cpu only machine
